[tool.black]
line-length = 79
skip-string-normalization = true
target-version = ["py39", "py310", "py311", "py312", "py313"]

# Ref: https://github.com/codespell-project/codespell#using-a-config-file
[tool.codespell]
check-hidden = true
# ignore-regex = ""
ignore-words-list = "checkin,debbugs,subtile,subtiles"

# https://black.readthedocs.io/en/stable/guides/using_black_with_other_tools.html#flake8
# requires Flake8-pyproject
[tool.flake8]
extend-ignore = ["E203"]
# we configure black to match flake8's default line length of 79

[tool.isort]
profile = "black"
force_sort_within_sections = true
line_length = 79

[tool.mypy]
namespace_packages = false
python_version = "3.9"
strict = true
